config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :videos do
    resources :comments
    member do
  		put "like" => 'videos#upvote'
  		put "unlike" => 'videos#downvote'
		end
	end
  resources :users
	resources :profile do
    collection do
      get :favourites
      get :uploads
    end
  end
  get 'welcome/home'
  get 'tags/:tag', to: 'videos#index', as: :tag
  root 'welcome#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
  has_many :comments
  mount_uploader :avatar, AvatarUploader
  extend FriendlyId
  friendly_id :username, use: :slugged
end

app/models/video.rb
class Video < ApplicationRecord
	acts_as_taggable
	acts_as_votable
	is_impressionable
	extend FriendlyId
	friendly_id :title, use: :slugged
	belongs_to :user
	has_many :comments, dependent: :destroy

	# def url=(url)
	# 	url.nil? ? write_attribute(:url, url.scan(/.*=(.*)/)[0][0]) : url
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]

	def index
    @comments = Comment.all
  end

	def new
    @comment = current_user.comments.build
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
  	@comment = current_user.comments.build(comment_params)
    @comment.video_id = params[:video_id]
    if @comment.save
    	redirect_to request.referrer
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.present?
    	@comment.destroy
    end
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_action :set_user
	def index
	end

	def uploads
		@myuploads = @user.videos.all
	end

	def favourites
		@favourites = @user.videos.all
	end

	private

	def set_user
		@user = User.find(current_user)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]
    
    def index
        @users = User.all
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
          if @user.update(user_params)
            format.html { redirect_to request.referer, notice: 'Video was successfully updated.' }
            format.json { render :show, status: :ok, location: request.referer }
          else
            format.html { render :edit }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
    end
    
    private
    
    def set_user
        @user = User.friendly.find(params[:id])
    end
    
    def user_params
        params.require(:user).permit(:username, :name, :bio, :avatar)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_video, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    if params[:tag]
      @videos = Video.tagged_with(params[:tag])
    else
      @videos = Video.all
    end
  end

  def show
    impressionist(@video)
    @comment = Comment.new
    @comment.video_id = @video.id
    @comments = @video.comments
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @video.upvote_from current_user
    redirect_to video_path
  end

  def downvote
    @video.downvote_from current_user
    redirect_to video_path
  end

  private
    def set_video
      @video = Video.friendly.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :url, :description, :tag_list)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  	@videos = Video.all
  	@recent_videos = Video.take 3
  	@most_viewed_videos = Video.take 3
  	@popular_video = Video.order(:created_at)
  	@tags = ActsAsTaggableOn::Tag.where(taggings_count: 1)
  	@user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@video, @comment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body %>
    <%= f.association :video %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learn Party</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="app-layout">
  	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">

          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <%= link_to 'Learn Party', root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right">
              <!-- Authentication Links -->
              <% if user_signed_in? %>
                <li id="user-avatar">
                  <%= link_to profile_index_path do %>
                    <%= image_tag(current_user.avatar_url(:thumbnail), class: "img-circle") %>
                  <% end %>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <%= current_user.name || current_user.email %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <%= link_to profile_index_path do %>
                          <i class="fa fa-btn fa-user"></i> <%= current_user.name || current_user.email %>'s profile
                      <% end %>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to uploads_profile_index_path do %>
                        <i class="fa fa-btn fa-dashboard"></i> Dashboard
                      <% end %>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-btn fa-power-off"></i> Logout
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to 'login', new_user_session_path %></li>
                <li><%= link_to 'Register', new_user_registration_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>

    <div id="footer">
      <strong>Made with <i class="fa fa-heart"></i>
      <span class="incognito-text">By</span> <a href="https://github.com/victorjambo" target="_blank">VM</a></strong>
      <span class="pull-right">
        <strong> #TIA 2017</strong>
      </span>
    </div>

    <!-- JavaScripts -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/edit.html.erb
<div class="col-md-5 col-md-offsets-1">
    <h2>Update Profile</h2>
    
    <%= simple_form_for @user do |f| %>
        <div class="form-group">
            <%= f.input :email %>
        </div>
        <div class="form-group">
            <%= f.input :username, id: "username" %>
        </div>
        <div class="form-group">
            <%= f.input :name, id: "name" %>
        </div>
        <div class="form-group">
            <%= f.input :bio, id: "about", input_html: { cols: "50", rows: "10" } %>
        </div>
        <div class="form-group">
            <%= button_tag type: 'submit', id: "update-profile", class: "btn btn-primary"  do %>
                <i class="fa fa-btn fa-user"></i> Update Profile
            <% end %>
        </div>
    <% end %>
    
</div>

app/views/users/index.html.erb
<ul>
    <% @users.each do |user| %>
        <li><%= user.email %> ~ <%= link_to 'show', user %> ~ <%= link_to 'edit', edit_user_path(user) %></li>
    <% end %>
</ul>

app/views/users/show.html.erb
<div id="main-content" class="container-fluid">


  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">

        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Videos By Category</h3>
            </div>
            <div class="panel-body popular-videos">
              <span class="badge"><a href="http://learn-party.herokuapp.com">All</a></span>


              <span class="badge">
                                <a href="http://learn-party.herokuapp.com/category/pop">pop</a>
                            </span>


            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Popular - Most Viewed</h3>
            </div>
            <div class="panel-body popular-videos">

              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/3">Classic Man </a>
                                <span class="incognito-text">(89)</span>
                            </h5>


              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/1">Little Bit More </a>
                                <span class="incognito-text">(83)</span>
                            </h5>


              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/2">afsds </a>
                                <span class="incognito-text">(44)</span>
                            </h5>

            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Popular - Most Liked</h3>
            </div>
            <div class="panel-body popular-videos">

              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/1">Little Bit More </a>
                                <span class="incognito-text">(1)</span>
                            </h5>


              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/4">ljljlj </a>
                                <span class="incognito-text">(1)</span>
                            </h5>


              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/5">Rust keynote </a>
                                <span class="incognito-text">(1)</span>
                            </h5>

            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Popular - Most commented on</h3>
            </div>
            <div class="panel-body popular-videos">

              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/1">Little Bit More </a>
                                <span class="incognito-text">(1)</span>
                            </h5>


              <h5 class="top-videos">
                                <i class="fa fa-youtube-play"></i>
                                <a href="http://learn-party.herokuapp.com/videos/4">ljljlj </a>
                                <span class="incognito-text">(1)</span>
                            </h5>

            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Top video publishers</h3>
            </div>
            <div class="panel-body popular-videos">


              <span class="badge">
                                    <a href="http://learn-party.herokuapp.com/users/1">John Kariuki</a>
                                    <span class="incognito-text">(1)</span>
              </span>


              <span class="badge">
                                    <a href="http://learn-party.herokuapp.com/users/32">john</a>
                                    <span class="incognito-text">(1)</span>
              </span>


              <span class="badge">
                                    <a href="http://learn-party.herokuapp.com/users/24">tyler malin</a>
                                    <span class="incognito-text">(1)</span>
              </span>


              <span class="badge">
                                    <a href="http://learn-party.herokuapp.com/users/19">victor mutai</a>
                                    <span class="incognito-text">(1)</span>
              </span>


              <span class="badge">
                                    <a href="http://learn-party.herokuapp.com/users/15">Fayez Mubarqui</a>
                                    <span class="incognito-text">(1)</span>
              </span>


            </div>
          </div>
        </div>
      </div>
      
      <!-- content -->
      <div class="col-md-9">
        <div class="col-md-12" style="margin-bottom: 50px;">
          <div class="row">
            <div id="user-profile">
              <div class="col-md-4">
                <h4>About <%= link_to @user.name || @user.email, @user %></h4>
                <%= image_tag(@user.avatar_url, style: "height:250px;border-radius: 5px;") %>
                <p><%= @user.bio %></p>
              </div>
              <div class="col-md-8">
                <h4>
                    <%= @user.videos.last %>
                </h4>
                <iframe width="100%" height="325" src="http://www.youtube.com/embed/<%= @user.videos.last.url %>" allowfullscreen></iframe>
              </div>
            </div>
          </div>
        </div>
        <h3>Videos Posted by <%= link_to @user.name || @user.email, @user %></h3>
        <hr>
        <div id="video-library">



          <div class="row">

            <% @user.videos.each do |video| %>
            <div class="col-sm-4 col-md-4">
              <%= link_to video do %>
                <img class="video-iframe" src="http://img.youtube.com/vi/<%= video.url %>/0.jpg" allowfullscreen="">
              <% end %>
              <span class="pull-right dashboard-float">
                <%= link_to video, id: "favorite_video", class: "favorite_video" do %>
                  <i class="fa fa-heart likesVideo"></i>
                  <span class="favorites-count incognito-text"> <%= video.get_upvotes.size %></span>
                <% end %>
              </span>
              <section class="video">
                <div class="title">
                  <h4><%= link_to video.title, video %></h4>
                </div>
                <p><%= video.title %></p>
              </section>
            </div>
          <% end %>

          </div>


        </div>
      </div>
    </div>
  </div>

app/views/videos/_comment.html.erb
<% @comments.each do |comment| %>
	<li class="media">
		<a class="media-left" href="#">
			<img class="media-object img-circle img-thumbnail" src="https://avatars.githubusercontent.com/u/16223627?v=3" alt="John Kariuki" style="width:100px;">
		</a>
		<div class="media-body">
			<div class="well">
				<h4 class="media-heading">John Kariuki</h4>
				<h6 class="pull-right"><%= time_ago_in_words(comment.updated_at) %> ago</h6>
				<p class="media-comment"><%= comment.body %></p>
			</div>
		</div>
	</li>
<% end %>

app/views/videos/edit.html.erb
<div id="main-content" class="container-fluid">
	<div class="row">
		<div class="col-md-3">
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to "#{current_user.name}'s Profile", profile_index_path %>
				</li>
				<li class="list-group-item">
					<%= link_to 'Add New video', new_video_path %>
				</li>
				<li class="list-group-item">
					<%= link_to 'My Uploaded videos', uploads_profile_index_path %>
				</li>
				<li class="list-group-item">
					<%= link_to 'My Favorited Videos', favourites_profile_index_path %>
				</li>
			</ul>
		</div>
		<div class="col-md-9">
			<h1>Editing Video</h1>
			<%= render 'form', video: @video %>
		</div>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.url %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<div id="main-content" class="container-fluid">
	<div class="row">
		<div class="col-md-3">
			<ul class="list-group">
				<li class="list-group-item">
					<%= link_to "#{current_user.name}'s Profile", profile_index_path %>
				</li>
				<li class="list-group-item active">
					<%= link_to 'Add New video', new_video_path %>
				</li>
				<li class="list-group-item">
					<%= link_to 'My Uploaded videos', uploads_profile_index_path %>
				</li>
				<li class="list-group-item">
					<%= link_to 'My Favorited Videos', favourites_profile_index_path %>
				</li>
			</ul>
		</div>
		<div class="col-md-5 col-md-offsets-1">
			<h2>New Video</h2>
			<%= render 'form', video: @video %>
		</div>
		
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div id="main-content" class="container-fluid">
	<div class="container">
    <div class="col-md-12">
      <h2><%= @video.title %></h2>
      <iframe width="100%" height="500" src="http://www.youtube.com/embed/<%= @video.url %>" allowfullscreen></iframe>
    </div>
    <div class="col-md-12">
      <div id="video-info" class="well">
        <ul class="stats-summary pull-left">
          <li>
            <i class="fa fa-comment"></i> 
            <span id="commentsCount">0</span>
          </li>
          <li>
            <%= link_to like_video_path(@video), id: "favorite_video", data: { placement: "bottom" }, method: :put, remote: :true do %>
              <i class="fa fa-heart"></i>
              <span class="favorites-count">
              	<%= @video.get_upvotes.size %>
            	</span>
            <% end %>
          </li>
          <li>
            <i class="fa fa-eye"></i> 
            <%= @video.impressionist_count(filter: :session_hash, filter: :ip_address) %>
          </li>
        </ul>
        <div class="pull-right">            
          Created by 
          <a href="http://learn-party.herokuapp.com/users/32"> john</a>
          <span class="incognito-text"><%= time_ago_in_words(@video.updated_at) %></span>
        </div>
      </div>
    </div>

    <!-- category -->
    <div class="col-md-3">
      <div id="video-tags" class="well">
      	<% @video.tag_list.each do |tag| %>
      		<span class="badge">
	      		<%= link_to tag, tag_path(tag) %>
	      	</span>
      	<% end %>
      </div>
    </div>

    <!-- description -->
    <div class="col-md-9">
      <div id="video-description" class="well">
        <p><%= @video.title %> description</p>
        <p><%= raw @video.tag_list.map{ |tag| link_to tag, tag_path(tag) }.join(', ') %></p>
        <p><%= @video.description %></p>
      </div>
    </div>

    <!-- comments -->
    <div class="col-md-12">
      <div class="row">
        <ul class="nav nav-tabs" role="tablist" id="comment-section">
          <li class="active">
          	<a href="#all-comments" role="tab" data-toggle="tab">Comments</a>
          </li>
          <li>
          	<% if user_signed_in? %>
          		<a href="#new-comment" role="tab" data-toggle="tab">Add comment</a>
          	<% end %>
          </li>              
        </ul>
        <div id="commentSection" class="tab-content">
          <div class="tab-pane active" id="all-comments">
            <ul class="media-list">
							<%= render partial: 'comment' %>
            </ul>
          </div>

					<!-- add comment -->
          <% if user_signed_in? %>  
	          <div class="tab-pane" id="new-comment">
	            <div id="feedback">
	              <div class="alert alert-danger alert-dismissible" role="alert" style="display: none;">
	                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	                	<span aria-hidden="true">×</span>
	                </button>
	                Error. No comment provided or error processing request. Please try again.
	              </div>
	            </div>
              <%= render partial: 'comments/form' %>
	          </div>
            <% end %>

          </div>
        </div>
      </div>
  </div>
</div>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/upvote.js.erb
$('.favorites-count').hmtl('<%= @video.get_upvotes.size %>')

app/views/welcome/home.html.erb
<div id="landing-page" class="text-center">
  <section class="landing-page-title">
    <h1>Welcome to the <strong class="site-highlight">Learn Party</strong></h1>
    <h2>Get the best learning materials online. <strong class="site-highlight">On Demand. </strong></h2>
    <hr>
    <div class="landing-page-call-to-action">
      <% if user_signed_in? %>
        <%= link_to 'ADD NEW VIDEO', new_video_path, class: "btn btn-default" %>
        <%= link_to 'VIEW MY PROFILE', profile_index_path, class: "btn btn-success" %>

      <% else %>
      	<%= link_to 'LOGIN', new_user_session_path,class: "btn btn-default"  %>
      	<%= link_to 'REGISTER', new_user_registration_path, class: "btn btn-success" %>
      <% end %>
    </div>
  </section>
  <a href="#main-content" id="scroll-to-content"><i class="fa fa-chevron-circle-down"></i></a>
</div>

<div id="main-content" class="container-fluid">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Videos By Category</h3>
            </div>
            <div class="panel-body popular-videos">
              <span class="badge"><%= link_to 'All', videos_path %></span>
              <% @tags.each do |tag| %>
                <span class="badge">
                	<%= link_to tag.name, tag_path(tag.name) %>
              	</span>
              <% end %>
            </div>
          </div>
        </div>
          <div class="col-md-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <h3 class="panel-title">Popular - Most Viewed</h3>
                  </div>
                  <div class="panel-body popular-videos">
                    <% @popular_video.each  do |popular_video|%>
                      <h5 class="top-videos">
                        <i class="fa fa-youtube-play"></i>
                        <%= link_to popular_video.title, popular_video %>
                        <span class="incognito-text">(<%= popular_video.impressionist_count %>)</span>
                      </h5>
                    <% end %>
                  </h5>
                  </div>
              </div>
          </div>
          <div class="col-md-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Popular - Most Liked</h3>
                  </div>
                  <div class="panel-body popular-videos">
                    <% @videos.each do |video| %>
                      <h5 class="top-videos">
                        <i class="fa fa-youtube-play"></i>
                        <%= link_to video.title, video %>
                        <span class="incognito-text">(<%= video.get_upvotes.size %>)</span>
                      </h5>
                    <% end %>
                  </div>
              </div>
          </div>
          <div class="col-md-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <h3 class="panel-title">Popular - Most commented on</h3>
                  </div>
                  <div class="panel-body popular-videos">
                    <% @videos.each do |video| %>
                      <h5 class="top-videos">
                        <i class="fa fa-youtube-play"></i>
                        <%= link_to video.title, video %>
                        <span class="incognito-text">(<%= video.comments.size%>)</span>
                    </h5>
                  <% end %>
                  </div>
              </div>
          </div>
          <div class="col-md-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <h3 class="panel-title">Top video publishers</h3>
                  </div>
                  <div class="panel-body popular-videos">
                    <% @user.each do |user| %>
                      <span class="badge">
                        <%= link_to user.name, user %>
                        <span class="incognito-text">(<%= user.videos.size %>)</span>
                      </span>
                    <% end %>
                  </div>
              </div>
          </div>
      </div>
      <div class="col-md-9">
        <div id="video-library">
          <div class="row">
            <% @recent_videos.each do |recent_video| %>
              <div class="col-sm-4 col-md-4">
                <%= link_to recent_video do %>
                  <img class="video-iframe" src="http://img.youtube.com/vi/<%= recent_video.url %>/0.jpg" allowfullscreen="">
                <% end %>
                <section class="video">
                  <div class="title">
                    <h4>
                      <%= link_to recent_video.title, recent_video %>
                    </h4>
                  </div>
                    <p><%= recent_video.description %></p>
                </section>
              </div>
            <% end %>
          </div>
          <div class="row">
            <% @most_viewed_videos.each do |most_viewed_video| %>
              <div class="col-sm-4 col-md-4">
                <%= link_to most_viewed_video do %>
                  <img class="video-iframe" src="http://img.youtube.com/vi/<%= most_viewed_video.url %>/0.jpg" allowfullscreen="">
                <% end %>
                <section class="video">
                  <div class="title">
                    <h4>
                      <%= link_to most_viewed_video.title, most_viewed_video %>
                    </h4>
                  </div>
                    <p><%= most_viewed_video.description %></p>
                </section>
              </div>
            <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>